#!/usr/bin/env python3
"""Create a GitHub PR for loop results. Called by GitHub Actions."""
import sys, os, subprocess, json

title = sys.argv[1] if len(sys.argv) > 1 else "Loop Engineering complete"
goal = os.environ.get("LOOP_GOAL", "")
trigger = os.environ.get("LOOP_TRIGGER", "")
iterations = os.environ.get("LOOP_ITERATIONS", "")
run_url = os.environ.get("RUN_URL", "")

body = f"""## Loop Engineering Results

**Goal:** {goal}
**Trigger:** {trigger}
**Iterations:** {iterations}
**Status:** SUCCESS

**Run:** {run_url}

_This PR was auto-generated by the ECC-to-Hermes Loop Engineering system._
"""

# Write body to temp file
body_file = "/tmp/pr_body.md"
with open(body_file, "w") as f:
    f.write(body)

# Git setup
subprocess.run(["git", "config", "user.name", "Hermes Loop Bot"], check=True)
subprocess.run(["git", "config", "user.email", "hermes-loop-bot@users.noreply.github.com"], check=True)

# Create branch and commit
branch = f"hermes-loop/fix-{subprocess.run(['date', '+%Y%m%d-%H%M%S'], capture_output=True, text=True).stdout.strip()}"
subprocess.run(["git", "checkout", "-b", branch], check=True)
subprocess.run(["git", "add", "-A"], check=True)
commit_msg = f"""🤖 Loop Engineering: {goal}

Trigger: {trigger}
Iterations: {iterations}
Run: {run_url}"""
subprocess.run(["git", "commit", "-m", commit_msg], check=True)
subprocess.run(["git", "push", "origin", branch, "-f"], check=True, capture_output=True)

# Create PR
result = subprocess.run(
    ["gh", "pr", "create", "--title", title, "--body-file", body_file, "--base", "main"],
    capture_output=True, text=True
)
print(result.stdout.strip() or result.stderr.strip())
